config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:show, :create, :new] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    collection do
      get 'top' => 'cocktails#top'
    end
  end
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
  root 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  def average_score
    reviews_count = self.reviews.length
    return "" if reviews_count == 0
    score_sum = 0
    self.reviews.each do |review|
      score_sum += review.stars
    end
    average_score = score_sum/reviews_count
  end

  def empty_stars
    5 - average_score.to_i
  end

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: {scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
  has_many :cocktails, through: :doses
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :stars, presence: true, inclusion: {in: [0, 1, 2, 3, 4, 5], message: "Invalid value!"}
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to(new_cocktail_dose_path(@cocktail))
    else
      render(:new)
    end
  end

  def new
    @cocktail = Cocktail.new()
  end

  def top
    @cocktails = Cocktail.joins(:reviews).where('stars > 2')
  end

private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @dose = Dose.new()
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to(cocktail_path(@cocktail))
    else
      render(:new)
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to(cocktail_path(@cocktail))
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to(cocktail_path(@cocktail))
    else
      render(:new)
    end
  end

  def destroy
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def review_params
    params.require(:review).permit(:stars, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(135,48,0,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'bar.jpg' %>');">

  <div class="banner-content">
    <h1>Enter your personal bar</h1>
    <p>Store the secrets of your favourite elixirs</p>
      <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

<h3> Your masterpieces</h2>
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-xs-6 col-md-3">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
            <div>
              <h2 class="card-name">
                <%= cocktail.name %>
              </h2>
              <ul class="card-list">
                <% cocktail.doses.each do |dose| %>
                  <li>
                    <%= dose.ingredient.name %>
                  </li>
                <% end %>
              </ul>
              <div class="card-reviews">
                <% cocktail.average_score.to_i.times do %>
                  <i class="fas fa-star"></i>
                <% end %>
                <% cocktail.empty_stars.to_i.times do %>
                  <i class="far fa-star"></i>
                <% end %>
              </div>
            </div>
            <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-4 col-md-offset-4">
      <div class= "form">
          <%= simple_form_for @cocktail do |f| %>
            <%= f.input :name %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= f.submit class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(255,255,255,0), rgba(0,0,0,0.78)), url('<%= cl_image_path @cocktail.photo, height: 500, width: 500, crop: :fill %>'); background-size: cover">
  <div class="show-banner-content">
    <div class="show-banner-name">
      <%= @cocktail.name %>
    </div>
    <div class="show-card-reviews">
      <% @cocktail.average_score.to_i.times do %>
        <i class="fas fa-star"></i>
        <% end %>
      <% @cocktail.empty_stars.to_i.times do %>
        <i class="far fa-star"></i>
        <% end %>
      </div>
    <div class="show-review-number">
      <%= "(#{@cocktail.reviews.length} reviews)" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-2 col-md-offset-5">
      <ul class= "ingrediens-list">
        <% @cocktail.doses.each do |dose| %>
        <li class= "single-ingredient">
          <span class="ingredient-full">
            <%= dose.ingredient.name %>
            <%= dose.description %>
          </span>
          <%= link_to "", dose_path(dose), method: :delete, class: "far fa-times-circle" %>
        </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-12 col-md-4 col-md-offset-4">
      <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>
      <%= link_to "Add a review", new_cocktail_review_path(@cocktail)%>
    </div>
  </div>

  <div class="row reviews-row">
    <% @cocktail.reviews.each do |review| %>
      <div class="col-xs-12 col-md-3">
        <div class="review-card">
          <% review.stars.times do %>
          <i class="fas fa-star"></i>
          <% end %>
          <% (5 - review.stars.to_i).times do %>
          <i class="far fa-star"></i>
          <% end %>
          <p class="review-description"><%= review.description %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-4 col-md-offset-4">
      <h1>New dose for <%= @cocktail.name %></h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.association :ingredient %>
        <%= f.input :description %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-4 col-md-offset-4">
      <h1>New review for <%= @cocktail.name %></h1>
      <%= simple_form_for [@cocktail, @review] do |f| %>
        <%= f.input :stars %>
        <%= f.input :description %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Add a cocktail", new_cocktail_path , class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_reviews.html.erb
<% cocktail.average_score.to_i.times do %>
  <i class="fas fa-star"></i>
  <% end %>
<% cocktail.empty_stars.to_i.times do %>
  <i class="far fa-star"></i>
<% end %>